'use strict';

module.exports.DRIVER_STATUS_RESPONSE = 'DRIVER_STATUS_RESPONSE';
module.exports.DRIVER_STATUS_REQUEST = 'DRIVER_STATUS_REQUEST';
module.exports.DRIVER_GEOLOCATION = 'DRIVER_GEOLOCATION';